#include "quota_portal.h"

#include "quota_json.h"
#include "quota_portable_service.h"
#include "quota_testable.h"

#include "cJSON.h"
#include "esp_http_server.h"
#include "esp_timer.h"
#include "lwip/sockets.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CSP_BYTES 512

static httpd_handle_t s_server;
static quota_portal_callbacks_t s_callbacks;
static char s_secret[QUOTA_PORTABLE_ACCESS_CODE_BYTES + 1];
static char s_csp[CSP_BYTES];
QUOTA_TESTABLE unsigned s_failures;

/* The one static setup page, generated by tools/build_setup_page.mjs. */
extern const unsigned char setup_html_start[] __asm__("_binary_setup_page_html_start");
extern const unsigned char setup_html_end[] __asm__("_binary_setup_page_html_end");

bool quota_portal_host_is_valid(const char *host)
{
    return host != NULL &&
           (strcmp(host, "192.168.4.1") == 0 || strcmp(host, "192.168.4.1:80") == 0);
}

bool quota_portal_origin_is_valid(const char *origin)
{
    return origin != NULL && (strcmp(origin, "http://192.168.4.1") == 0 ||
                              strcmp(origin, "http://192.168.4.1:80") == 0);
}

bool quota_portal_secret_matches(const char *expected, const char *supplied)
{
    if (expected == NULL || supplied == NULL ||
        strlen(expected) != QUOTA_PORTABLE_ACCESS_CODE_BYTES ||
        strlen(supplied) != QUOTA_PORTABLE_ACCESS_CODE_BYTES)
        return false;
    unsigned difference = 0;
    for (size_t i = 0; i < QUOTA_PORTABLE_ACCESS_CODE_BYTES; i++)
        difference |= (unsigned char)expected[i] ^ (unsigned char)supplied[i];
    return difference == 0;
}

bool quota_portal_access_code_is_valid(const char *code)
{
    if (code == NULL || strlen(code) != QUOTA_PORTABLE_ACCESS_CODE_BYTES)
        return false;
    for (size_t i = 0; i < QUOTA_PORTABLE_ACCESS_CODE_BYTES; i++) {
        char ch = code[i];
        if (i % 5 == 4) {
            if (ch != '-')
                return false;
        } else if (!((ch >= '0' && ch <= '9') || (ch >= 'A' && ch <= 'Z')) || ch == 'I' ||
                   ch == 'L' || ch == 'O' || ch == 'U') {
            return false;
        }
    }
    return true;
}

void quota_portal_clear_json(cJSON *json)
{
    for (cJSON *item = json; item; item = item->next) {
        if (item->child)
            quota_portal_clear_json(item->child);
        if (item->valuestring)
            quota_portable_clear_secret(item->valuestring, strlen(item->valuestring));
        if (item->string)
            quota_portable_clear_secret(item->string, strlen(item->string));
    }
}

static bool copy_text(const cJSON *object, const char *name, char *output, size_t capacity,
                      bool required, bool empty)
{
    const cJSON *item = cJSON_GetObjectItemCaseSensitive(object, name);
    if (item == NULL)
        return !required;
    if (!cJSON_IsString(item) || item->valuestring == NULL)
        return false;
    size_t length = strlen(item->valuestring);
    if (length >= capacity || (!empty && length == 0) ||
        !quota_utf8_is_valid(item->valuestring, length))
        return false;
    for (size_t i = 0; i < length; i++) {
        unsigned char ch = (unsigned char)item->valuestring[i];
        if (ch < 0x20 || ch == 0x7f)
            return false;
    }
    memcpy(output, item->valuestring, length + 1);
    return true;
}

static bool unsigned_field(const cJSON *object, const char *name, uint64_t maximum,
                           uint64_t *output, bool required)
{
    const cJSON *item = cJSON_GetObjectItemCaseSensitive(object, name);
    if (item == NULL)
        return !required;
    if (!cJSON_IsNumber(item) || !isfinite(item->valuedouble) || item->valuedouble < 0 ||
        item->valuedouble > (double)maximum || floor(item->valuedouble) != item->valuedouble)
        return false;
    *output = (uint64_t)item->valuedouble;
    return true;
}

static bool bool_field(const cJSON *object, const char *name, bool *output, bool required)
{
    const cJSON *item = cJSON_GetObjectItemCaseSensitive(object, name);
    if (item == NULL)
        return !required;
    if (!cJSON_IsBool(item))
        return false;
    *output = cJSON_IsTrue(item);
    return true;
}

static bool keys_allowed(const cJSON *object, const char *const *extra)
{
    for (const cJSON *item = object->child; item != NULL; item = item->next) {
        bool allowed = strcmp(item->string, "v") == 0 || strcmp(item->string, "op") == 0 ||
                       strcmp(item->string, "request_id") == 0 ||
                       strcmp(item->string, "phone_utc") == 0;
        for (size_t i = 0; !allowed && extra[i] != NULL; i++)
            allowed = strcmp(item->string, extra[i]) == 0;
        if (!allowed)
            return false;
    }
    return true;
}

static bool network_password_valid(const quota_portable_command_t *command)
{
    size_t length = strlen(command->password);
    if (length == 0)
        return command->open_network;
    if (command->open_network)
        return false;
    if (length >= 8 && length <= 63)
        return true;
    if (length != 64)
        return false;
    for (size_t i = 0; i < length; i++) {
        char ch = command->password[i];
        if (!((ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F')))
            return false;
    }
    return true;
}

bool quota_portal_parse_command(const char *json, size_t length, quota_portable_command_t *command)
{
    if (command == NULL)
        return false;
    memset(command, 0, sizeof(*command));
    if (json == NULL || length == 0 || length > QUOTA_PORTABLE_COMMAND_BYTES ||
        !quota_json_text_bounded(json, length))
        return false;
    command->network_index = UINT8_MAX;
    const char *end = NULL;
    cJSON *root = cJSON_ParseWithLengthOpts(json, length, &end, false);
    bool ok = root != NULL && end != NULL;
    if (ok) {
        while (end < json + length && (*end == ' ' || *end == '\n' || *end == '\r' || *end == '\t'))
            end++;
        ok = end == json + length && quota_json_unique_keys(root);
    }
    uint64_t version = 0;
    char op[32] = {0};
    if (ok)
        ok = unsigned_field(root, "v", QUOTA_PROTOCOL_VERSION, &version, true) &&
             version == QUOTA_PROTOCOL_VERSION &&
             unsigned_field(root, "phone_utc", 4102444800ULL, &command->phone_utc, false) &&
             copy_text(root, "request_id", command->request_id, sizeof(command->request_id), true,
                       false) &&
             quota_json_is_lower_hex(command->request_id, 8) &&
             copy_text(root, "op", op, sizeof(op), true, false);
    static const char *const network_keys[] = {"ssid",          "password",     "phone_utc",
                                               "network_index", "open_network", NULL};
    static const char *const network_remove_keys[] = {"network_index", NULL};
    static const char *const deepseek_keys[] = {"account_id", "api_key", "label", NULL};
    static const char *const account_keys[] = {"account_id", NULL};
    static const char *const codex_keys[] = {"account_id", "label", NULL};
    static const char *const settings_keys[] = {"refresh_seconds", "auto_refresh",
                                                "screen_timeout_seconds", NULL};
    static const char *const cancel_keys[] = {"target_request_id", NULL};
    static const char *const no_keys[] = {NULL};
    const char *const *allowed = no_keys;
    if (ok && strcmp(op, "network_save") == 0) {
        command->op = QUOTA_PORTABLE_OP_NETWORK_SAVE;
        allowed = network_keys;
        uint64_t index = UINT8_MAX;
        ok = unsigned_field(root, "network_index", QUOTA_PORTABLE_NETWORKS - 1, &index, false) &&
             copy_text(root, "ssid", command->ssid, sizeof(command->ssid), true, false) &&
             copy_text(root, "password", command->password, sizeof(command->password), false,
                       true) &&
             bool_field(root, "open_network", &command->open_network, false) &&
             network_password_valid(command);
        command->network_index = (uint8_t)index;
    } else if (ok && strcmp(op, "network_remove") == 0) {
        command->op = QUOTA_PORTABLE_OP_NETWORK_REMOVE;
        allowed = network_remove_keys;
        uint64_t index = 0;
        ok = unsigned_field(root, "network_index", QUOTA_PORTABLE_NETWORKS - 1, &index, true);
        command->network_index = (uint8_t)index;
    } else if (ok && strcmp(op, "deepseek_save") == 0) {
        command->op = QUOTA_PORTABLE_OP_DEEPSEEK_SAVE;
        allowed = deepseek_keys;
        ok = copy_text(root, "account_id", command->account_id, sizeof(command->account_id), false,
                       false) &&
             copy_text(root, "api_key", command->api_key, sizeof(command->api_key), false, false) &&
             copy_text(root, "label", command->label, sizeof(command->label), true, false) &&
             (command->account_id[0] == 0 || quota_id_is_valid(command->account_id)) &&
             (command->api_key[0] != 0 || command->account_id[0] != 0);
    } else if (ok && strcmp(op, "codex_queue") == 0) {
        command->op = QUOTA_PORTABLE_OP_CODEX_QUEUE;
        allowed = codex_keys;
        ok = copy_text(root, "account_id", command->account_id, sizeof(command->account_id), false,
                       false) &&
             copy_text(root, "label", command->label, sizeof(command->label), false, true) &&
             (command->account_id[0] == 0 || quota_id_is_valid(command->account_id));
    } else if (ok && strcmp(op, "account_remove") == 0) {
        command->op = QUOTA_PORTABLE_OP_ACCOUNT_REMOVE;
        allowed = account_keys;
        ok = copy_text(root, "account_id", command->account_id, sizeof(command->account_id), true,
                       false) &&
             quota_id_is_valid(command->account_id);
    } else if (ok && strcmp(op, "settings_save") == 0) {
        command->op = QUOTA_PORTABLE_OP_SETTINGS_SAVE;
        allowed = settings_keys;
        uint64_t refresh = 0, timeout = 0;
        ok = unsigned_field(root, "refresh_seconds", UINT16_MAX, &refresh, true) &&
             unsigned_field(root, "screen_timeout_seconds", UINT16_MAX, &timeout, true) &&
             bool_field(root, "auto_refresh", &command->auto_refresh, true) &&
             quota_refresh_seconds_is_valid(refresh) && quota_screen_timeout_is_valid(timeout);
        command->refresh_seconds = (uint16_t)refresh;
        command->screen_timeout_seconds = (uint16_t)timeout;
    } else if (ok && strcmp(op, "operation_cancel") == 0) {
        command->op = QUOTA_PORTABLE_OP_OPERATION_CANCEL;
        allowed = cancel_keys;
        ok = copy_text(root, "target_request_id", command->target_request_id,
                       sizeof(command->target_request_id), true, false) &&
             quota_json_is_lower_hex(command->target_request_id, 8);
    } else if (ok && strcmp(op, "setup_close") == 0)
        command->op = QUOTA_PORTABLE_OP_SETUP_CLOSE;
    else if (ok && strcmp(op, "validate") == 0)
        command->op = QUOTA_PORTABLE_OP_VALIDATE;
    else if (ok && strcmp(op, "refresh") == 0)
        command->op = QUOTA_PORTABLE_OP_REFRESH;
    else if (ok && strcmp(op, "reconnect") == 0)
        command->op = QUOTA_PORTABLE_OP_RECONNECT;
    else
        ok = false;
    if (ok)
        ok = keys_allowed(root, allowed);
    /* cJSON also owns copies of API keys/passwords. Clear its string values. */
    quota_portal_clear_json(root);
    cJSON_Delete(root);
    if (!ok)
        quota_portable_clear_secret(command, sizeof(*command));
    return ok;
}

/* Every error names the protocol and firmware, so a page of another version can tell. */
static esp_err_t reply_error(httpd_req_t *request, const char *status, const char *code)
{
    char body[160];
    int length =
        snprintf(body, sizeof(body),
                 "{\"ok\":false,\"error_code\":\"%s\",\"protocol\":%d,\"firmware\":\"%s\"}", code,
                 QUOTA_PROTOCOL_VERSION, quota_portable_service_firmware());
    httpd_resp_set_status(request, status);
    httpd_resp_set_type(request, "application/json");
    httpd_resp_set_hdr(request, "Cache-Control", "no-store");
    return httpd_resp_send(request, body,
                           length > 0 && (size_t)length < sizeof(body) ? length
                                                                       : HTTPD_RESP_USE_STRLEN);
}

static bool header(httpd_req_t *request, const char *name, char *value, size_t capacity)
{
    size_t bytes = httpd_req_get_hdr_value_len(request, name);
    return bytes != 0 && bytes < capacity &&
           httpd_req_get_hdr_value_str(request, name, value, capacity) == ESP_OK;
}

static bool socket_ipv4_address(int socket, bool peer, uint32_t *ip)
{
    struct sockaddr_storage address = {0};
    socklen_t length = sizeof(address);
    int result = peer ? getpeername(socket, (struct sockaddr *)&address, &length)
                      : getsockname(socket, (struct sockaddr *)&address, &length);
    if (result != 0)
        return false;
    if (address.ss_family == AF_INET) {
        if (length < sizeof(struct sockaddr_in))
            return false;
        *ip = ntohl(((const struct sockaddr_in *)&address)->sin_addr.s_addr);
        return true;
    }
#if defined(AF_INET6) && (!defined(LWIP_IPV6) || LWIP_IPV6)
    if (address.ss_family == AF_INET6) {
        if (length < sizeof(struct sockaddr_in6))
            return false;
        const struct sockaddr_in6 *ipv6 = (const struct sockaddr_in6 *)&address;
        static const unsigned char mapped_prefix[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff};
        /* IDF's dual-stack HTTP socket returns IPv4 clients as ::ffff:a.b.c.d.
         * Native IPv6 and the deprecated IPv4-compatible form stay denied. */
        if (memcmp(ipv6->sin6_addr.s6_addr, mapped_prefix, sizeof(mapped_prefix)) != 0)
            return false;
        uint32_t ipv4;
        memcpy(&ipv4, ipv6->sin6_addr.s6_addr + sizeof(mapped_prefix), sizeof(ipv4));
        *ip = ntohl(ipv4);
        return true;
    }
#endif
    return false;
}

static bool peer_is_ap(httpd_req_t *request)
{
    uint32_t peer, local;
    int socket = httpd_req_to_sockfd(request);
    return socket_ipv4_address(socket, true, &peer) && socket_ipv4_address(socket, false, &local) &&
           local == 0xc0a80401U && (peer & 0xffffff00U) == 0xc0a80400U && (peer & 0xffU) > 1 &&
           (peer & 0xffU) < 255;
}

static bool access_locked(void)
{
    return s_failures >= QUOTA_PORTABLE_ACCESS_FAILURES;
}

static bool authorize(httpd_req_t *request, bool secret, bool mutation, const char **denial)
{
    char host[32] = {0}, supplied[QUOTA_PORTABLE_ACCESS_CODE_BYTES + 1] = {0}, origin[40] = {0};
    if (denial != NULL)
        *denial = "session_expired";
    if (s_callbacks.session_active == NULL || !s_callbacks.session_active(s_callbacks.context))
        return false;
    if (denial != NULL)
        *denial = "unauthorized";
    bool ok = peer_is_ap(request) && header(request, "Host", host, sizeof(host)) &&
              quota_portal_host_is_valid(host);
    /* Five wrong codes in a row lock the hotspot, even against the right code, until the user
     * opens a new hotspot session on the Passport. */
    if (ok && secret && access_locked()) {
        if (denial != NULL)
            *denial = "access_locked";
        ok = false;
    }
    if (ok && secret) {
        ok = header(request, "X-AIQ-Access", supplied, sizeof(supplied)) &&
             quota_portal_secret_matches(s_secret, supplied);
        if (ok)
            s_failures = 0; /* five wrong codes in a row, not five over the whole session */
        if (!ok && supplied[0] != 0 && s_failures < QUOTA_PORTABLE_ACCESS_FAILURES) {
            s_failures++;
            if (denial != NULL && access_locked())
                *denial = "access_locked";
        }
    }
    if (ok && mutation)
        ok = header(request, "Origin", origin, sizeof(origin)) &&
             quota_portal_origin_is_valid(origin);
    if (ok && !mutation && httpd_req_get_hdr_value_len(request, "Origin") != 0)
        ok = header(request, "Origin", origin, sizeof(origin)) &&
             quota_portal_origin_is_valid(origin);
    quota_portable_clear_secret(supplied, sizeof(supplied));
    return ok;
}

/* The page names its own meta Content-Security-Policy; the response header repeats it and adds
 * frame-ancestors, which a meta tag cannot carry. Without that tag nothing but framing is
 * allowed. */
QUOTA_TESTABLE size_t portal_csp(const char *html, size_t length, char *out, size_t capacity)
{
    static const char marker[] = "http-equiv=\"Content-Security-Policy\" content=\"";
    static const char frame[] = "; frame-ancestors 'none'";
    size_t used = 0;
    if (capacity <= sizeof(frame) + sizeof("default-src 'none'")) {
        if (capacity)
            out[0] = 0;
        return 0;
    }
    for (size_t i = 0; i + sizeof(marker) < length; i++) {
        if (memcmp(html + i, marker, sizeof(marker) - 1) != 0)
            continue;
        const char *start = html + i + sizeof(marker) - 1;
        const char *end = memchr(start, '"', length - (size_t)(start - html));
        if (end == NULL || (size_t)(end - start) + sizeof(frame) > capacity)
            break;
        used = (size_t)(end - start);
        memcpy(out, start, used);
        break;
    }
    if (used == 0)
        used = (size_t)snprintf(out, capacity, "default-src 'none'");
    if (used + sizeof(frame) > capacity)
        used = 0;
    memcpy(out + used, frame, sizeof(frame));
    return used + sizeof(frame) - 1;
}

static esp_err_t page_handler(httpd_req_t *request)
{
    const char *denial;
    if (!authorize(request, false, false, &denial))
        return reply_error(request, "403 Forbidden", denial);
    httpd_resp_set_type(request, "text/html; charset=utf-8");
    httpd_resp_set_hdr(request, "Cache-Control", "no-store");
    httpd_resp_set_hdr(request, "X-Content-Type-Options", "nosniff");
    httpd_resp_set_hdr(request, "Referrer-Policy", "no-referrer");
    httpd_resp_set_hdr(request, "X-Frame-Options", "DENY");
    httpd_resp_set_hdr(request, "Content-Security-Policy", s_csp);
    size_t length = (size_t)(setup_html_end - setup_html_start);
    if (length != 0 && setup_html_start[length - 1] == 0)
        length--;
    return httpd_resp_send(request, (const char *)setup_html_start, length);
}

static esp_err_t state_handler(httpd_req_t *request)
{
    const char *denial;
    if (!authorize(request, true, false, &denial))
        return reply_error(request, "403 Forbidden", denial);
    char *body = malloc(QUOTA_PORTABLE_STATE_BYTES + 1);
    if (body == NULL)
        return reply_error(request, "503 Service Unavailable", "busy");
    size_t length = 0;
    bool ok = s_callbacks.state_json(body, QUOTA_PORTABLE_STATE_BYTES + 1, &length,
                                     s_callbacks.context) &&
              length != 0 && length <= QUOTA_PORTABLE_STATE_BYTES;
    esp_err_t result;
    if (!ok)
        result = reply_error(request, "503 Service Unavailable", "state_unavailable");
    else if (!authorize(request, true, false, &denial))
        result = reply_error(request, "403 Forbidden", denial);
    else {
        httpd_resp_set_type(request, "application/json");
        httpd_resp_set_hdr(request, "Cache-Control", "no-store");
        result = httpd_resp_send(request, body, length);
    }
    free(body);
    return result;
}

static esp_err_t command_handler(httpd_req_t *request)
{
    const char *denial;
    if (!authorize(request, true, true, &denial))
        return reply_error(request, "403 Forbidden", denial);
    char content_type[64] = {0};
    if (!header(request, "Content-Type", content_type, sizeof(content_type)) ||
        (strcmp(content_type, "application/json") != 0 &&
         strcmp(content_type, "application/json; charset=utf-8") != 0))
        return reply_error(request, "415 Unsupported Media Type", "invalid_content_type");
    if (request->content_len == 0 || request->content_len > QUOTA_PORTABLE_COMMAND_BYTES)
        return reply_error(request, "413 Payload Too Large", "invalid_size");
    char body[QUOTA_PORTABLE_COMMAND_BYTES + 1];
    size_t received = 0;
    int64_t deadline = esp_timer_get_time() + 3000000;
    while (received < request->content_len) {
        if (esp_timer_get_time() >= deadline) {
            quota_portable_clear_secret(body, sizeof(body));
            return reply_error(request, "408 Request Timeout", "incomplete_request");
        }
        int count = httpd_req_recv(request, body + received, request->content_len - received);
        if (count <= 0) {
            quota_portable_clear_secret(body, sizeof(body));
            return reply_error(request, "400 Bad Request", "incomplete_request");
        }
        received += (size_t)count;
    }
    body[received] = 0;
    quota_portable_command_t command;
    bool ok = quota_portal_parse_command(body, received, &command);
    quota_portable_clear_secret(body, sizeof(body));
    if (!ok)
        return reply_error(request, "400 Bad Request", "invalid_command");
    quota_portable_submit_result_t submitted = QUOTA_PORTABLE_SUBMIT_CLOSED;
    bool authorized = authorize(request, true, true, &denial);
    if (authorized)
        submitted = s_callbacks.submit(&command, s_callbacks.context);
    char ack[80];
    int length = snprintf(ack, sizeof(ack), "{\"request_id\":\"%.8s\",\"accepted\":true}",
                          command.request_id);
    quota_portable_clear_secret(&command, sizeof(command));
    if (!authorized)
        return reply_error(request, "403 Forbidden", denial);
    if (submitted != QUOTA_PORTABLE_SUBMIT_ACCEPTED) {
        if (submitted == QUOTA_PORTABLE_SUBMIT_BUSY)
            return reply_error(request, "503 Service Unavailable", "busy");
        if (submitted == QUOTA_PORTABLE_SUBMIT_CONFLICT)
            return reply_error(request, "409 Conflict", "request_conflict");
        if (submitted == QUOTA_PORTABLE_SUBMIT_INVALID)
            return reply_error(request, "400 Bad Request", "invalid_command");
        return reply_error(request, "403 Forbidden", "session_expired");
    }
    httpd_resp_set_status(request, "202 Accepted");
    httpd_resp_set_type(request, "application/json");
    httpd_resp_set_hdr(request, "Cache-Control", "no-store");
    return httpd_resp_send(request, ack, length);
}

bool quota_portal_start(const char *secret, const quota_portal_callbacks_t *callbacks)
{
    if (s_server != NULL)
        return false;
    if (secret == NULL || !quota_portal_access_code_is_valid(secret) || callbacks == NULL ||
        callbacks->submit == NULL || callbacks->state_json == NULL ||
        callbacks->session_active == NULL)
        return false;
    s_callbacks = *callbacks;
    memcpy(s_secret, secret, sizeof(s_secret));
    s_failures = 0;
    (void)portal_csp((const char *)setup_html_start, (size_t)(setup_html_end - setup_html_start),
                     s_csp, sizeof(s_csp));
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.stack_size = 8192;
    config.max_open_sockets = 2;
    config.max_uri_handlers = 3;
    config.lru_purge_enable = true;
    config.recv_wait_timeout = 3;
    config.send_wait_timeout = 3;
    if (httpd_start(&s_server, &config) != ESP_OK) {
        quota_portal_stop();
        return false;
    }
    const httpd_uri_t routes[] = {
        {.uri = "/", .method = HTTP_GET, .handler = page_handler},
        {.uri = "/api/state", .method = HTTP_GET, .handler = state_handler},
        {.uri = "/api/command", .method = HTTP_POST, .handler = command_handler},
    };
    for (size_t i = 0; i < sizeof(routes) / sizeof(routes[0]); i++) {
        if (httpd_register_uri_handler(s_server, &routes[i]) != ESP_OK) {
            quota_portal_stop();
            return false;
        }
    }
    return true;
}

void quota_portal_stop(void)
{
    if (s_server != NULL) {
        if (httpd_stop(s_server) != ESP_OK)
            return;
        s_server = NULL;
    }
    quota_portable_clear_secret(s_secret, sizeof(s_secret));
    memset(&s_callbacks, 0, sizeof(s_callbacks));
}
