#include "quota_portable_service.h"
#include "quota_direct.h"
#include "quota_store.h"
#include "quota_portal.h"
#include "sdk.h"
#include <assert.h>
#include <stdlib.h>
#include <string.h>
static uint64_t now_ms=100, wall=1800000000;
static bool common_locked,pairing,connected,network_ok=true,store_fail,cache_fail,acquire_fail;
static unsigned config_generation=1,query_calls,refresh_calls,retry_calls,release_calls;
static quota_service_view_t public_view;
static quota_portable_config_t saved_config;
static quota_direct_credential_t credentials[QUOTA_MAX_ACCOUNTS];
static bool used[QUOTA_MAX_ACCOUNTS];
static quota_snapshot_t saved_cache;
static quota_direct_credential_t *acquired;
static quota_portal_callbacks_t portal;
static bool portal_active;
static void unlocked(void){assert(!common_locked);}
static int fake_gettimeofday(struct timeval *out,void *zone){(void)zone;out->tv_sec=(time_t)wall;out->tv_usec=0;return 0;}
static int fake_settimeofday(const struct timeval *in,const struct timezone *zone){(void)zone;wall=(uint64_t)in->tv_sec;return 0;}
#define gettimeofday fake_gettimeofday
#define settimeofday fake_settimeofday
#include "quota_portable_service.c"
#undef gettimeofday
#undef settimeofday
struct quota_direct{quota_direct_hooks_t hooks;quota_direct_credential_t *pending;bool active;};
static struct quota_direct provider;
static quota_direct_result_code_t query_code=QUOTA_DIRECT_OK,refresh_code=QUOTA_DIRECT_OK,login_code=QUOTA_DIRECT_WAITING;
int64_t esp_timer_get_time(void){return (int64_t)now_ms*1000;}
uint32_t esp_random(void){static uint32_t n=7;return n++;}
size_t esp_get_free_heap_size(void){return 60000;}
size_t esp_get_minimum_free_heap_size(void){return 1000;}
size_t heap_caps_get_largest_free_block(int caps){(void)caps;return 30000;}
UBaseType_t uxTaskGetStackHighWaterMark(void *task){(void)task;return 1024;}
static esp_netif_t netif;
esp_netif_t *esp_netif_create_default_wifi_ap(void){unlocked();return &netif;}
esp_netif_t *esp_netif_get_handle_from_ifkey(const char *key){(void)key;unlocked();return &netif;}
esp_err_t esp_netif_get_ip_info(esp_netif_t *n,esp_netif_ip_info_t *out){(void)n;unlocked();out->ip.addr=connected?1:0;return ESP_OK;}
esp_err_t esp_wifi_set_mode(int mode){(void)mode;unlocked();return ESP_OK;}
static wifi_config_t wifi_config;
esp_err_t esp_wifi_set_config(int iface,const wifi_config_t *value){unlocked();if(iface==WIFI_IF_STA)wifi_config=*value;return ESP_OK;}
esp_err_t esp_wifi_connect(void){unlocked();connected=network_ok;return ESP_OK;}
esp_err_t esp_wifi_disconnect(void){unlocked();connected=false;return ESP_OK;}
esp_err_t esp_wifi_sta_get_ap_info(wifi_ap_record_t *out){unlocked();if(!connected)return ESP_FAIL;memset(out,0,sizeof(*out));memcpy(out->ssid,wifi_config.sta.ssid,32);return ESP_OK;}
esp_err_t esp_netif_sntp_init(const esp_sntp_config_t *config){(void)config;unlocked();return ESP_OK;}
esp_err_t esp_netif_sntp_sync_wait(unsigned timeout){(void)timeout;unlocked();return ESP_OK;}
void esp_netif_sntp_deinit(void){unlocked();}
bool quota_portal_start(const char *secret,const quota_portal_callbacks_t *callbacks){unlocked();assert(strlen(secret)==43);portal=*callbacks;portal_active=true;return true;}
void quota_portal_stop(void){unlocked();portal_active=false;}
bool quota_portal_running(void){return portal_active;}
bool quota_store_init(void){unlocked();return true;}
quota_store_read_result_t quota_store_load_config_result(quota_portable_config_t *out){unlocked();*out=saved_config;return QUOTA_STORE_READ_OK;}
bool quota_store_load_config(quota_portable_config_t *out){unlocked();*out=saved_config;return true;}
bool quota_store_save_config(const quota_portable_config_t *in){unlocked();if(store_fail)return false;saved_config=*in;return true;}
quota_portable_credential_t *quota_store_credential_acquire(void){unlocked();if(acquired||acquire_fail)return NULL;acquired=calloc(1,sizeof(*acquired));return acquired;}
void quota_store_credential_release(quota_portable_credential_t *value){unlocked();assert(value==acquired);assert(provider.pending!=value);quota_portable_clear_secret(value,sizeof(*value));free(value);acquired=NULL;release_calls++;}
static quota_store_read_result_t credential_read_error=QUOTA_STORE_READ_OK;
quota_store_read_result_t quota_store_load_credential_result(uint8_t slot,quota_portable_credential_t *out){unlocked();assert(out==acquired);memset(out,0,sizeof(*out));if(credential_read_error!=QUOTA_STORE_READ_OK)return credential_read_error;if(!used[slot])return QUOTA_STORE_READ_MISSING;*out=credentials[slot];return QUOTA_STORE_READ_OK;}
bool quota_store_load_credential(uint8_t slot,quota_portable_credential_t *out){return quota_store_load_credential_result(slot,out)==QUOTA_STORE_READ_OK;}
bool quota_store_save_credential(uint8_t slot,const quota_portable_credential_t *in){unlocked();assert(in==acquired);if(store_fail)return false;credentials[slot]=*in;used[slot]=true;return true;}
bool quota_store_remove_credential(uint8_t slot,const char *id,uint32_t gen){unlocked();assert(!acquired);if(store_fail)return false;memset(&credentials[slot],0,sizeof(credentials[slot]));strcpy(credentials[slot].id,id);credentials[slot].slot=slot;credentials[slot].generation=gen;credentials[slot].provider=QUOTA_PROVIDER_CODEX;credentials[slot].tombstone=true;used[slot]=true;return true;}
bool quota_store_save_snapshot(const quota_snapshot_t *in,const quota_portable_account_ref_t *refs,size_t count,uint64_t epoch){unlocked();(void)refs;(void)count;(void)epoch;if(cache_fail)return false;saved_cache=*in;return true;}
bool quota_store_load_snapshot(const quota_portable_account_ref_t *refs,size_t count,uint64_t epoch,quota_snapshot_t *out){unlocked();(void)refs;(void)count;(void)epoch;*out=saved_cache;return true;}
quota_direct_t *quota_direct_create(const quota_direct_hooks_t *hooks,quota_direct_transport_t transport,void *context){unlocked();(void)transport;(void)context;provider.hooks=*hooks;return &provider;}
void quota_direct_destroy(quota_direct_t *direct){(void)direct;}
bool quota_direct_has_pending_persist(const quota_direct_t *direct){return direct&&direct->pending;}
void quota_direct_login_cancel(quota_direct_t *direct){if(direct)direct->active=false;}
static quota_direct_result_t answer(quota_direct_result_code_t code,const quota_direct_credential_t *c){quota_direct_result_t r={0};r.code=code;r.http_status=200;if(code==QUOTA_DIRECT_OK){r.source_valid=true;r.source_epoch=wall;strcpy(r.account.id,c->id);r.account.provider=c->provider;r.account.has_observed_at=true;r.account.observed_at=wall;r.account.status=QUOTA_STATUS_OK;}if(code==QUOTA_DIRECT_RATE_LIMITED)r.retry_after_seconds=90;return r;}
quota_direct_result_t quota_direct_login_begin(quota_direct_t *direct,const quota_direct_credential_t *c,uint64_t time,uint64_t epoch){unlocked();(void)time;(void)epoch;assert(direct->hooks.admit(NULL,c->id,c->generation));direct->active=true;return answer(QUOTA_DIRECT_WAITING,c);}
quota_direct_result_t quota_direct_login_step(quota_direct_t *direct,quota_direct_credential_t *c,uint64_t time,uint64_t epoch){unlocked();(void)time;(void)epoch;if(login_code==QUOTA_DIRECT_PERSIST_PENDING){strcpy(c->access_token,"received-login-token");c->auth_state=QUOTA_PORTABLE_AUTH_READY;direct->pending=c;}return answer(login_code,c);}
void quota_direct_login_view(const quota_direct_t *direct,uint64_t time,quota_direct_login_view_t *out){(void)time;memset(out,0,sizeof(*out));out->active=direct->active;strcpy(out->verification_url,"https://auth.openai.com/codex/device");strcpy(out->user_code,"fake-code");}
quota_direct_result_t quota_direct_refresh(quota_direct_t *direct,quota_direct_credential_t *c,uint64_t epoch){unlocked();(void)epoch;refresh_calls++;assert(direct->hooks.admit(NULL,c->id,c->generation));if(refresh_code==QUOTA_DIRECT_PERSIST_PENDING){strcpy(c->refresh_token,"received-rotation");direct->pending=c;}return answer(refresh_code,c);}
quota_direct_result_t quota_direct_query(quota_direct_t *direct,quota_direct_credential_t *c,uint64_t epoch){unlocked();(void)epoch;if(!direct->hooks.admit(NULL,c->id,c->generation))return answer(QUOTA_DIRECT_DEFERRED,c);query_calls++;return answer(query_code,c);}
quota_direct_result_t quota_direct_retry_persist(quota_direct_t *direct){unlocked();retry_calls++;assert(direct->pending==acquired);if(!direct->hooks.persist(NULL,direct->pending))return answer(QUOTA_DIRECT_PERSIST_PENDING,direct->pending);quota_direct_result_t out=answer(QUOTA_DIRECT_OK,direct->pending);direct->pending=NULL;return out;}
const char *quota_direct_error_name(quota_direct_result_code_t code){(void)code;return "fake";}
static void common_lock(void){assert(!common_locked);common_locked=true;}
static void common_unlock(void){assert(common_locked);common_locked=false;}
static bool common_try(void){if(common_locked)return false;common_lock();return true;}
static uint32_t generation_locked(void){assert(common_locked);return config_generation;}
static void changed_locked(void){assert(common_locked);config_generation++;}
static bool pairing_requested(void){return pairing;}
static bool wifi_ready(void){unlocked();return true;}
static bool wifi_stop(void){unlocked();connected=false;return true;}
static void notify(void){unlocked();}
static void hook_wake(void){unlocked();}
static bool display_current(uint32_t generation){(void)generation;return !s_sleeping;}

static quota_model_t durable_model;
static uint64_t durable_sequence;
static quota_store_read_result_t model_read_error=QUOTA_STORE_READ_OK;
static bool model_fail,model_unknown,model_apply_unknown;
quota_store_read_result_t quota_store_load_model_result(quota_model_t *out,uint64_t *sequence){unlocked();if(model_read_error!=QUOTA_STORE_READ_OK)return model_read_error;if(!durable_sequence)return QUOTA_STORE_READ_MISSING;*out=durable_model;*sequence=durable_sequence;return QUOTA_STORE_READ_OK;}
quota_model_write_result_t quota_store_save_model_verified(uint64_t previous,const quota_model_t *candidate,uint64_t sequence){unlocked();if(!quota_catalog_valid(candidate))fprintf(stderr,"invalid model networks=%u selected=%u refresh=%u timeout=%u entries=%u intent=%u\n",candidate->network_count,candidate->selected_network,candidate->refresh_seconds,candidate->screen_timeout_seconds,candidate->entry_count,candidate->intent.kind);assert(quota_catalog_valid(candidate));if(durable_sequence==sequence&&!memcmp(candidate,&durable_model,sizeof(*candidate)))return QUOTA_MODEL_APPLIED;if(model_unknown){if(model_apply_unknown){durable_model=*candidate;durable_sequence=sequence;}return QUOTA_MODEL_WRITE_UNKNOWN;}if(model_fail||store_fail)return QUOTA_MODEL_NOT_APPLIED;assert(durable_sequence==previous);durable_model=*candidate;durable_sequence=sequence;return QUOTA_MODEL_APPLIED;}
bool quota_store_save_observations(const quota_model_t *model,const quota_snapshot_t *snapshot,uint64_t time){unlocked();(void)model;(void)time;if(cache_fail)return false;saved_cache=*snapshot;return true;}
quota_store_read_result_t quota_store_load_observations(const quota_model_t *model,uint64_t time,quota_snapshot_t *snapshot){unlocked();(void)model;(void)time;for(unsigned i=0;i<saved_cache.account_count;i++){int index=quota_find_account_by_id(snapshot,saved_cache.accounts[i].id);if(index>=0)quota_catalog_copy_observation(snapshot,(size_t)index,&saved_cache,i);}return QUOTA_STORE_READ_OK;}
static quota_snapshot_t collector_snapshot;
static unsigned collector_reads,collector_refreshes;
static bool collector_ok=true;
static quota_store_read_result_t inventory_error=QUOTA_STORE_READ_OK;
static quota_store_read_result_t legacy_inventory(quota_snapshot_t *out){unlocked();if(inventory_error!=QUOTA_STORE_READ_OK)return inventory_error;*out=collector_snapshot;return QUOTA_STORE_READ_OK;}
static bool legacy_snapshot(const quota_legacy_endpoint_t *endpoint,bool refresh,uint32_t generation,quota_snapshot_t *out,bool *deferred){unlocked();assert(endpoint->enabled);(void)generation;*deferred=!quota_portable_service_http_allowed();if(*deferred)return false;collector_reads++;if(refresh)collector_refreshes++;if(!collector_ok)return false;*out=collector_snapshot;return true;}
static const quota_device_config_t *legacy_input;
static quota_store_read_result_t legacy_primary_error=QUOTA_STORE_READ_OK;
static uint16_t legacy_timeout=120;
static unsigned legacy_primary_calls;
static quota_store_read_result_t legacy_config(quota_device_config_t *out,uint16_t *timeout){unlocked();legacy_primary_calls++;if(legacy_primary_error!=QUOTA_STORE_READ_OK)return legacy_primary_error;if(!legacy_input)return QUOTA_STORE_READ_MISSING;*out=*legacy_input;*timeout=legacy_timeout;return QUOTA_STORE_READ_OK;}
static void initialize(void){saved_config.mode=QUOTA_MODE_DIRECT;saved_config.refresh_seconds=300;saved_config.auto_refresh=true;saved_config.screen_timeout_seconds=120;saved_config.network_count=1;strcpy(saved_config.networks[0].ssid,"old-hotspot");strcpy(saved_config.networks[0].password,"password");for(unsigned i=0;i<2;i++){used[i]=true;credentials[i].slot=i;credentials[i].generation=1;credentials[i].provider=i?QUOTA_PROVIDER_DEEPSEEK:QUOTA_PROVIDER_CODEX;credentials[i].auth_state=QUOTA_PORTABLE_AUTH_READY;snprintf(credentials[i].id,sizeof(credentials[i].id),"%032x",i+1);strcpy(credentials[i].server_account_id,"fake-server");strcpy(credentials[i].access_token,"old-access");strcpy(credentials[i].refresh_token,"old-refresh");strcpy(credentials[i].api_key,"old-key");credentials[i].expires_at=wall+3600;}saved_cache.account_count=1;saved_cache.refresh_seconds=300;saved_cache.accounts[0].provider=QUOTA_PROVIDER_CODEX;strcpy(saved_cache.accounts[0].id,credentials[0].id);saved_cache.accounts[0].has_observed_at=true;saved_cache.accounts[0].observed_at=wall;saved_cache.accounts[0].five_hour.present=true;saved_cache.accounts[0].five_hour.remaining_percent=17;}
static void boot_legacy(const quota_device_config_t *legacy){legacy_input=legacy;quota_portable_service_hooks_t hooks={.view=&public_view,.lock=common_lock,.unlock=common_unlock,.try_lock=common_try,.config_generation_locked=generation_locked,.config_changed_locked=changed_locked,.pairing_requested=pairing_requested,.wifi_ready=wifi_ready,.wifi_stop=wifi_stop,.notify=notify,.wake=hook_wake,.display_current=display_current,.legacy_inventory=legacy_inventory,.legacy_snapshot=legacy_snapshot,.legacy_config=legacy_config};assert(quota_portable_service_init(legacy,&hooks));}
static void boot(void){boot_legacy(NULL);}
static void tick(bool sleeping){quota_portable_service_tick(sleeping,1);assert(!common_locked);}
static void ready(void){tick(false);now_ms+=500;tick(false);assert(public_view.portable.network_state==QUOTA_PORTABLE_NETWORK_READY);}
static void phone(void){quota_portable_service_open();tick(false);assert(portal_active&&public_view.portable.setup_ready);}
static void submit_command(quota_portable_command_t *command){command->phone_utc=wall;assert(portal.submit(command,NULL)==QUOTA_PORTABLE_SUBMIT_ACCEPTED);tick(false);}
static job_t *job(const char *id){for(unsigned i=0;i<s_job_count;i++)if(!strcmp(s_jobs[i].id,id))return &s_jobs[i];assert(false);return NULL;}
static void close_phone(void){quota_portable_service_close();tick(false);now_ms+=500;ready();}
static void legacy_configuration(quota_device_config_t *legacy){memset(legacy,0,sizeof(*legacy));legacy->refresh_seconds=900;legacy->auto_refresh=false;legacy->server_time=wall;strcpy(legacy->ssid,"legacy-hotspot");strcpy(legacy->password,"password");strcpy(legacy->base_url,"https://192.168.1.2:4318");memset(legacy->pair_token,'a',QUOTA_PAIR_TOKEN_BYTES);strcpy(legacy->server_cert_pem,"-----BEGIN CERTIFICATE-----\nfake\n-----END CERTIFICATE-----");collector_snapshot.account_count=1;collector_snapshot.server_time=wall;collector_snapshot.refresh_seconds=3600;collector_snapshot.auto_refresh=false;collector_snapshot.accounts[0].provider=QUOTA_PROVIDER_CLAUDE;snprintf(collector_snapshot.accounts[0].id,sizeof(collector_snapshot.accounts[0].id),"%032x",99);strcpy(collector_snapshot.accounts[0].email,"legacy account");collector_snapshot.accounts[0].has_observed_at=true;collector_snapshot.accounts[0].observed_at=wall;collector_snapshot.accounts[0].five_hour.present=true;collector_snapshot.accounts[0].five_hour.remaining_percent=42;}
static void seed_model(void){model_defaults(&durable_model);durable_model.network_count=1;durable_model.networks[0]=saved_config.networks[0];durable_model.entry_count=2;for(unsigned i=0;i<2;i++){quota_catalog_entry_t *e=&durable_model.entries[i];strcpy(e->logical_id,credentials[i].id);e->provider=credentials[i].provider;e->source=QUOTA_ACCOUNT_DEVICE;e->activity=QUOTA_ACCOUNT_ACTIVE;e->row_generation=1;e->binding.native.slot=i;strcpy(e->binding.native.credential_id,credentials[i].id);e->binding.native.credential_generation=credentials[i].generation;}durable_sequence=1;}
static void seed_intent(void){seed_model();quota_model_intent_t *intent=&durable_model.intent;intent->kind=QUOTA_INTENT_UPSERT_NATIVE;intent->provider=QUOTA_PROVIDER_DEEPSEEK;intent->slot=1;strcpy(intent->logical_id,credentials[1].id);intent->expected_row_generation=1;strcpy(intent->previous_credential_id,credentials[1].id);intent->previous_credential_generation=1;strcpy(intent->target_credential_id,credentials[1].id);intent->target_credential_generation=2;strcpy(intent->desired_label,"recovered alias");}
static void all_native(void){for(unsigned i=2;i<8;i++){credentials[i]=credentials[1];credentials[i].slot=i;snprintf(credentials[i].id,sizeof(credentials[i].id),"%032x",i+1);used[i]=true;}}
int main(int argc,char **argv){assert(argc==2);initialize();
if(!strcmp(argv[1],"boot")){credentials[0].refresh_inflight=true;acquire_fail=true;boot();assert(!public_view.snapshot_valid);acquire_fail=false;now_ms+=5000;tick(false);assert(public_view.snapshot.account_count==2&&public_view.snapshot.accounts[0].five_hour.remaining_percent==17);assert(public_view.snapshot.accounts[0].status==QUOTA_STATUS_EXPIRED);assert(!public_view.snapshot.accounts[1].has_observed_at);assert(!acquired);}
else if(!strcmp(argv[1],"pending")){credentials[0].expires_at=1;refresh_code=QUOTA_DIRECT_PERSIST_PENDING;boot();ready();quota_portable_service_refresh();tick(false);assert(acquired&&provider.pending==acquired&&s_operation.kind==OP_SAVE);uint64_t due=s_operation.retry_at;assert(!quota_portable_service_prepare_pairing());unsigned http=refresh_calls+query_calls;store_fail=true;now_ms=due;tick(true);assert(retry_calls==1&&acquired);now_ms+=5000;tick(true);assert(retry_calls==2);store_fail=false;now_ms+=30000;tick(true);assert(!provider.pending&&!acquired&&s_operation.kind==OP_NONE);assert(refresh_calls+query_calls==http);assert(!strcmp(credentials[0].refresh_token,"received-rotation"));assert(quota_portable_service_next_deadline_ms(true)==UINT64_MAX);}
else if(!strcmp(argv[1],"key")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);strcpy(cmd.api_key,"candidate-key");strcpy(cmd.label,"candidate");submit_command(&cmd);assert(acquired&&!strcmp(credentials[1].api_key,"old-key"));assert(query_calls==0);close_phone();assert(!acquired&&!strcmp(credentials[1].api_key,"candidate-key"));assert(credentials[1].generation==2);assert(durable_model.intent.kind==QUOTA_INTENT_NONE);assert(!strcmp(durable_model.entries[1].label,"candidate"));assert(job(cmd.request_id)->state==2);}
else if(!strcmp(argv[1],"cancel")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);assert(public_view.snapshot.account_count==2&&durable_model.intent.kind==QUOTA_INTENT_UPSERT_NATIVE);quota_portable_command_t cancel={.op=QUOTA_PORTABLE_OP_OPERATION_CANCEL};strcpy(cancel.request_id,"22345678");strcpy(cancel.target_request_id,cmd.request_id);submit_command(&cancel);assert(!acquired&&public_view.snapshot.account_count==2);assert(durable_model.intent.kind==QUOTA_INTENT_NONE);assert(!strcmp(job(cmd.request_id)->error,"canceled"));}
else if(!strcmp(argv[1],"queue")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_NETWORK_SAVE,.network_index=0};strcpy(cmd.request_id,"12345678");strcpy(cmd.ssid,"new-hotspot");strcpy(cmd.password,"password");assert(portal.submit(&cmd,NULL)==QUOTA_PORTABLE_SUBMIT_ACCEPTED);assert(portal.submit(&cmd,NULL)==QUOTA_PORTABLE_SUBMIT_ACCEPTED);common_lock();config_generation++;common_unlock();tick(false);assert(!s_candidate_pending&&!strcmp(job(cmd.request_id)->error,"configuration_changed"));strcpy(cmd.request_id,"22345678");submit_command(&cmd);network_ok=false;quota_portable_service_close();tick(false);assert(s_candidate_pending);assert(public_view.portable.saved_network_count==1&&!strcmp(public_view.portable.saved_network_ssids[0],"old-hotspot"));now_ms+=25000;tick(false);assert(!s_candidate_pending&&!strcmp(durable_model.networks[0].ssid,"old-hotspot"));assert(job(cmd.request_id)->state==3);}
else if(!strcmp(argv[1],"cadence")){boot();ready();uint64_t deadline=s_next_refresh;tick(true);now_ms+=100;tick(false);assert(s_next_refresh==deadline);phone();assert(s_next_refresh==deadline);quota_portable_service_close();tick(false);assert(s_next_refresh==deadline);}
else if(!strcmp(argv[1],"pairing")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_CODEX_QUEUE};strcpy(cmd.request_id,"12345678");submit_command(&cmd);assert(acquired);quota_portable_command_t queued={.op=QUOTA_PORTABLE_OP_REFRESH};strcpy(queued.request_id,"22345678");assert(portal.submit(&queued,NULL)==QUOTA_PORTABLE_SUBMIT_ACCEPTED);pairing=true;tick(false);assert(s_count==1);assert(quota_portable_service_prepare_pairing());assert(!acquired&&!portal_active&&!s_queue);assert(!strcmp(job(queued.request_id)->error,"canceled"));unsigned calls=query_calls+refresh_calls;quota_portable_service_refresh();tick(false);assert(calls==query_calls+refresh_calls);}
else if(!strcmp(argv[1],"mixed")){quota_device_config_t legacy;legacy_configuration(&legacy);boot_legacy(&legacy);assert(public_view.snapshot.account_count==3);ready();collector_ok=false;quota_portable_service_refresh();for(unsigned i=0;i<5;i++){now_ms+=500;tick(false);}assert(query_calls>=2&&collector_reads>=1);assert(public_view.refresh_seconds==300);phone();quota_portable_command_t settings={.op=QUOTA_PORTABLE_OP_SETTINGS_SAVE,.refresh_seconds=900,.screen_timeout_seconds=120};strcpy(settings.request_id,"12345678");submit_command(&settings);assert(public_view.refresh_seconds==900&&job(settings.request_id)->state==2);char json[QUOTA_PORTABLE_STATE_BYTES];size_t length;assert(state_json(json,sizeof(json),&length,NULL));assert(strstr(json,"pending_accounts")&&!strstr(json,"pair_token")&&!strstr(json,"old-key")&&!strstr(json,"\"mode\""));}
else if(!strcmp(argv[1],"physical-gate")){boot();ready();assert(quota_portable_service_http_allowed());quota_portable_service_open();assert(!quota_portable_service_http_allowed());assert(!admit(NULL,credentials[0].id,1));tick(false);assert(portal_active);}
else if(!strcmp(argv[1],"typed-read")){credential_read_error=QUOTA_STORE_READ_IO_ERROR;boot();assert(!public_view.snapshot_valid&&!durable_sequence);assert(!strcmp(s_storage_error,"storage_io_error"));assert(!quota_portable_service_http_allowed());credential_read_error=QUOTA_STORE_READ_OK;now_ms+=5000;tick(false);assert(public_view.snapshot.account_count==2);}
else if(!strcmp(argv[1],"unknown")){boot();phone();model_unknown=true;model_apply_unknown=true;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_SETTINGS_SAVE,.refresh_seconds=900,.screen_timeout_seconds=120};strcpy(cmd.request_id,"12345678");submit_command(&cmd);assert(s_dirty_model&&public_view.refresh_seconds==300&&job(cmd.request_id)->state==1);assert(!quota_portable_service_http_allowed());model_unknown=false;now_ms+=1000;tick(true);assert(!s_dirty_model&&public_view.refresh_seconds==900&&job(cmd.request_id)->state==2);}
else if(!strcmp(argv[1],"delete")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_ACCOUNT_REMOVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);submit_command(&cmd);tick(false);assert(public_view.snapshot.account_count==1&&credentials[1].tombstone&&credentials[1].generation==2);assert(durable_model.intent.kind==QUOTA_INTENT_NONE);}
else if(!strcmp(argv[1],"generation")){credentials[1].generation=UINT32_MAX;boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);assert(job(cmd.request_id)->state==3&&!strcmp(job(cmd.request_id)->error,"generation_exhausted"));assert(!acquired);}
else if(!strcmp(argv[1],"upgrade")){quota_device_config_t legacy;legacy_configuration(&legacy);collector_snapshot.accounts[0].provider=QUOTA_PROVIDER_DEEPSEEK;boot_legacy(&legacy);phone();char logical[33];strcpy(logical,durable_model.entries[2].logical_id);quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,logical);strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);assert(durable_model.entries[2].source==QUOTA_ACCOUNT_LEGACY);close_phone();assert(durable_model.entries[2].source==QUOTA_ACCOUNT_DEVICE&&!strcmp(durable_model.entries[2].logical_id,logical));assert(durable_model.entries[2].row_generation==2);assert(!strcmp(public_view.snapshot.accounts[2].id,logical));}
else if(!strcmp(argv[1],"recovery-previous")){seed_intent();boot();assert(durable_model.intent.kind==QUOTA_INTENT_NONE&&durable_model.entries[1].binding.native.credential_generation==1);assert(!query_calls&&!refresh_calls&&!acquired);}
else if(!strcmp(argv[1],"recovery-target")){seed_intent();credentials[1].generation=2;strcpy(credentials[1].api_key,"durable-received-key");boot();assert(durable_model.intent.kind==QUOTA_INTENT_NONE&&durable_model.entries[1].binding.native.credential_generation==2&&durable_model.entries[1].row_generation==2);assert(!query_calls&&!refresh_calls&&!acquired);assert(!strcmp(durable_model.entries[1].label,"recovered alias"));}
else if(!strcmp(argv[1],"recovery-conflict")){seed_intent();used[1]=false;boot();assert(durable_model.intent.kind==QUOTA_INTENT_UPSERT_NATIVE&&!strcmp(s_storage_error,"recovery_conflict"));assert(!query_calls&&!refresh_calls&&!quota_portable_service_http_allowed());}
else if(!strcmp(argv[1],"invalid-model")){model_read_error=QUOTA_STORE_READ_INVALID;boot();assert(!durable_sequence&&!public_view.snapshot_valid&&!strcmp(s_storage_error,"storage_invalid"));now_ms+=10000;tick(false);assert(!durable_sequence&&!query_calls);}
else if(!strcmp(argv[1],"full-native")){all_native();boot();assert(public_view.snapshot.account_count==8);phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);assert(acquired);close_phone();assert(credentials[1].generation==2&&!acquired);}
else if(!strcmp(argv[1],"history-swap")){seed_model();quota_device_config_t legacy;legacy_configuration(&legacy);durable_model.legacy.enabled=true;durable_model.legacy.epoch=1;strcpy(durable_model.legacy.base_url,legacy.base_url);strcpy(durable_model.legacy.pair_token,legacy.pair_token);strcpy(durable_model.legacy.server_cert_pem,legacy.server_cert_pem);for(unsigned i=2;i<16;i++){quota_catalog_entry_t *e=&durable_model.entries[i];snprintf(e->logical_id,sizeof(e->logical_id),"%032x",i+100);e->provider=QUOTA_PROVIDER_CLAUDE;e->source=QUOTA_ACCOUNT_LEGACY;e->activity=i<8?QUOTA_ACCOUNT_ACTIVE:QUOTA_ACCOUNT_PENDING;e->row_generation=1;e->binding.legacy.endpoint_epoch=1;strcpy(e->binding.legacy.remote_id,e->logical_id);}durable_model.entry_count=16;boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_ACCOUNT_ACTIVATE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,durable_model.entries[8].logical_id);strcpy(cmd.replace_active_id,durable_model.entries[0].logical_id);submit_command(&cmd);assert(quota_catalog_count(&durable_model,QUOTA_ACCOUNT_ACTIVE)==8&&quota_catalog_count(&durable_model,QUOTA_ACCOUNT_PENDING)==8&&durable_model.entry_count==16);assert(durable_model.entries[8].activity==QUOTA_ACCOUNT_ACTIVE&&durable_model.entries[0].activity==QUOTA_ACCOUNT_PENDING);assert(used[0]&&!credentials[0].tombstone);}
else if(!strcmp(argv[1],"four-networks")){quota_device_config_t legacy;legacy_configuration(&legacy);saved_config.network_count=3;saved_config.selected_network=1;strcpy(saved_config.networks[1].ssid,"same-name");strcpy(saved_config.networks[1].password,"password-one");strcpy(saved_config.networks[2].ssid,"same-name");strcpy(saved_config.networks[2].password,"password-two");boot_legacy(&legacy);assert(durable_model.network_count==3&&durable_model.pending_network_present&&!strcmp(durable_model.pending_network.ssid,"legacy-hotspot"));assert(!strcmp(durable_model.networks[0].password,"password-one"));assert(public_view.portable.saved_network_count==3&&public_view.portable.pending_saved_network_present&&!strcmp(public_view.portable.pending_saved_network_ssid,"legacy-hotspot"));phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_NETWORK_ACTIVATE,.replace_index=2};strcpy(cmd.request_id,"12345678");submit_command(&cmd);close_phone();assert(!s_candidate_pending&&!strcmp(durable_model.networks[2].ssid,"legacy-hotspot")&&!strcmp(durable_model.pending_network.password,"password-two"));}
else if(!strcmp(argv[1],"id-collision")){quota_device_config_t legacy;legacy_configuration(&legacy);strcpy(collector_snapshot.accounts[0].id,credentials[0].id);boot_legacy(&legacy);assert(durable_model.entry_count==3&&strcmp(durable_model.entries[2].logical_id,credentials[0].id));assert(!strcmp(durable_model.entries[2].binding.legacy.remote_id,credentials[0].id));}
else if(!strcmp(argv[1],"endpoint-fence")){quota_device_config_t legacy;legacy_configuration(&legacy);boot_legacy(&legacy);strcpy(legacy.base_url,"https://192.168.1.3:4318");const char *error=NULL;assert(quota_portable_service_configure_legacy(&legacy,&error));assert(durable_model.legacy.epoch==2&&durable_model.entries[2].binding.legacy.endpoint_epoch==1&&public_view.snapshot.account_count==3);char json[QUOTA_PORTABLE_STATE_BYTES];size_t length;assert(state_json(json,sizeof(json),&length,NULL));assert(strstr(json,"source_changed"));}
else if(!strcmp(argv[1],"received-cancel")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);strcpy(cmd.api_key,"received-key");submit_command(&cmd);store_fail=true;close_phone();assert(acquired&&s_operation.kind==OP_SAVE&&s_operation.received);quota_portable_service_cancel_auth();quota_portable_service_open();pairing=true;tick(true);assert(acquired&&s_model.intent.kind==QUOTA_INTENT_UPSERT_NATIVE);unsigned http=query_calls+refresh_calls;store_fail=false;now_ms+=1000;tick(true);assert(!acquired&&!strcmp(credentials[1].api_key,"received-key")&&durable_model.intent.kind==QUOTA_INTENT_NONE);assert(query_calls+refresh_calls==http);}
else if(!strcmp(argv[1],"wake-cache-first")){quota_device_config_t legacy;legacy_configuration(&legacy);boot_legacy(&legacy);ready();s_next_refresh=now_ms;uint64_t deadline=s_next_refresh;tick(true);unsigned queries=query_calls,refreshes=collector_refreshes,reads=collector_reads;quota_portable_service_tick(false,2);now_ms+=500;quota_portable_service_tick(false,2);assert(query_calls==queries&&collector_refreshes==refreshes&&collector_reads==reads+1&&s_next_refresh==deadline);quota_portable_service_tick(false,2);assert(query_calls==queries+1&&s_next_refresh==deadline);}
else if(!strcmp(argv[1],"physical-login")){boot();phone();quota_portable_command_t queue={.op=QUOTA_PORTABLE_OP_CODEX_QUEUE};strcpy(queue.request_id,"12345678");submit_command(&queue);quota_portable_command_t launch={.op=QUOTA_PORTABLE_OP_CODEX_LAUNCH};strcpy(launch.request_id,"22345678");submit_command(&launch);close_phone();assert(s_operation.started);quota_portable_service_open();assert(!quota_portable_service_http_allowed());tick(false);assert(portal_active&&!acquired&&s_operation.kind==OP_NONE&&durable_model.intent.kind==QUOTA_INTENT_NONE);}
else if(!strcmp(argv[1],"full-native-upgrade-limit")){all_native();quota_device_config_t legacy;legacy_configuration(&legacy);collector_snapshot.accounts[0].provider=QUOTA_PROVIDER_DEEPSEEK;boot_legacy(&legacy);assert(durable_model.entry_count==9&&durable_model.entries[8].activity==QUOTA_ACCOUNT_PENDING);phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,durable_model.entries[8].logical_id);strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);assert(!acquired&&job(cmd.request_id)->state==3&&!strcmp(job(cmd.request_id)->error,"native_credential_limit"));assert(durable_model.entries[8].source==QUOTA_ACCOUNT_LEGACY);}
else if(!strcmp(argv[1],"received-model-unknown")){boot();phone();quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);strcpy(cmd.api_key,"received-key");submit_command(&cmd);model_unknown=true;model_apply_unknown=true;close_phone();assert(acquired&&s_dirty_model&&s_operation.kind==OP_SAVE);unsigned calls=query_calls;model_unknown=false;now_ms+=1000;tick(true);assert(!s_dirty_model&&!acquired&&s_model.intent.kind==QUOTA_INTENT_NONE&&credentials[1].generation==2);assert(query_calls==calls);}
else if(!strcmp(argv[1],"selection-collision")){quota_device_config_t legacy;legacy_configuration(&legacy);saved_config.mode=QUOTA_MODE_COMPANION;strcpy(legacy.selected_account_id,credentials[0].id);strcpy(collector_snapshot.accounts[0].id,credentials[0].id);boot_legacy(&legacy);assert(strcmp(durable_model.entries[2].logical_id,credentials[0].id)&&!strcmp(durable_model.selected_account_id,durable_model.entries[2].logical_id));assert(public_view.refresh_seconds==900);}
else if(!strcmp(argv[1],"inventory-io")){quota_device_config_t legacy;legacy_configuration(&legacy);inventory_error=QUOTA_STORE_READ_IO_ERROR;boot_legacy(&legacy);assert(!durable_sequence&&!strcmp(s_storage_error,"storage_io_error"));inventory_error=QUOTA_STORE_READ_OK;now_ms+=5000;tick(false);assert(durable_model.entry_count==3);}
else if(!strcmp(argv[1],"inventory-invalid")){quota_device_config_t legacy;legacy_configuration(&legacy);inventory_error=QUOTA_STORE_READ_INVALID;boot_legacy(&legacy);assert(!durable_sequence&&!strcmp(s_storage_error,"storage_invalid"));inventory_error=QUOTA_STORE_READ_OK;now_ms+=5000;tick(false);assert(!durable_sequence&&!query_calls);}
else if(!strcmp(argv[1],"sleep-open-deadline")){boot();tick(true);quota_portable_service_open();assert(quota_portable_service_next_deadline_ms(true)==UINT64_MAX);tick(true);assert(s_open&&!portal_active&&quota_portable_service_next_deadline_ms(true)==UINT64_MAX);tick(false);assert(portal_active);}
else if(!strcmp(argv[1],"prepare-unknown")){boot();phone();model_unknown=true;quota_portable_command_t queue={.op=QUOTA_PORTABLE_OP_CODEX_QUEUE};strcpy(queue.request_id,"12345678");submit_command(&queue);assert(s_dirty_model&&job(queue.request_id)->state==1&&public_view.portable.login_state==QUOTA_PORTABLE_LOGIN_QUEUED);model_unknown=false;now_ms+=1000;tick(false);assert(!s_dirty_model&&job(queue.request_id)->state==2&&durable_model.intent.kind==QUOTA_INTENT_UPSERT_NATIVE);quota_portable_command_t launch={.op=QUOTA_PORTABLE_OP_CODEX_LAUNCH};strcpy(launch.request_id,"22345678");submit_command(&launch);assert(job(launch.request_id)->state==1&&public_view.portable.login_state==QUOTA_PORTABLE_LOGIN_CONNECTING);}
else if(!strcmp(argv[1],"prepare-unknown-cancel")){boot();phone();model_unknown=true;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);quota_portable_command_t cancel={.op=QUOTA_PORTABLE_OP_OPERATION_CANCEL};strcpy(cancel.request_id,"22345678");strcpy(cancel.target_request_id,cmd.request_id);submit_command(&cancel);assert(s_operation.cancel_requested&&s_dirty_model&&acquired);model_unknown=false;now_ms+=1000;tick(false);assert(!s_dirty_model&&!acquired&&durable_model.intent.kind==QUOTA_INTENT_NONE&&job(cmd.request_id)->state==3&&!strcmp(job(cmd.request_id)->error,"canceled"));assert(!query_calls&&!refresh_calls);}
else if(!strcmp(argv[1],"unknown-corruption")){boot();phone();model_unknown=true;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_SETTINGS_SAVE,.refresh_seconds=900,.screen_timeout_seconds=120};strcpy(cmd.request_id,"12345678");submit_command(&cmd);model_read_error=QUOTA_STORE_READ_INVALID;now_ms+=1000;tick(true);assert(s_dirty_model&&s_recovery_blocked&&!strcmp(s_storage_error,"storage_invalid")&&public_view.refresh_seconds==300);assert(quota_portable_service_next_deadline_ms(true)==UINT64_MAX);}
else if(!strcmp(argv[1],"unknown-conflict")){boot();phone();model_unknown=true;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_SETTINGS_SAVE,.refresh_seconds=900,.screen_timeout_seconds=120};strcpy(cmd.request_id,"12345678");submit_command(&cmd);durable_sequence+=5;now_ms+=1000;tick(true);assert(s_dirty_model&&s_recovery_blocked&&!strcmp(s_storage_error,"recovery_conflict")&&public_view.refresh_seconds==300);assert(quota_portable_service_next_deadline_ms(true)==UINT64_MAX);}
else if(!strcmp(argv[1],"label-only-full")){all_native();credentials[1].generation=UINT32_MAX;boot();phone();uint32_t generation=durable_model.entries[1].row_generation;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.account_id,credentials[1].id);strcpy(cmd.label,"renamed alias");submit_command(&cmd);assert(job(cmd.request_id)->state==2&&!acquired&&credentials[1].generation==UINT32_MAX&&durable_model.entries[1].row_generation==generation&&!strcmp(durable_model.entries[1].label,"renamed alias"));assert(durable_model.intent.kind==QUOTA_INTENT_NONE&&!query_calls);}
else if(!strcmp(argv[1],"offline-deadlines")){quota_device_config_t legacy;legacy_configuration(&legacy);boot_legacy(&legacy);ready();s_model.auto_refresh=false;s_wake_read_pending=false;s_next_legacy_read=now_ms-1;s_cache_at=now_ms-1;s_cache_dirty=true;s_clock_ready=false;s_view.network_state=QUOTA_PORTABLE_NETWORK_ERROR;unsigned calls=query_calls+collector_reads;assert(quota_portable_service_next_deadline_ms(false)>now_ms);source_tick();assert(query_calls+collector_reads==calls);}
else if(!strcmp(argv[1],"dirty-expired-deadline")){boot();phone();model_unknown=true;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_DEEPSEEK_SAVE};strcpy(cmd.request_id,"12345678");strcpy(cmd.api_key,"candidate-key");submit_command(&cmd);now_ms+=QUOTA_PORTABLE_SETUP_MS+60001;tick(true);assert(s_dirty_model&&acquired&&quota_portable_service_next_deadline_ms(true)>now_ms);assert(!query_calls&&!refresh_calls);}
else if(!strcmp(argv[1],"legacy-config-retry")){quota_device_config_t legacy;legacy_configuration(&legacy);saved_config.mode=QUOTA_MODE_COMPANION;legacy_timeout=600;legacy_primary_error=QUOTA_STORE_READ_IO_ERROR;boot_legacy(&legacy);assert(!durable_sequence&&legacy_primary_calls==1&&!strcmp(s_storage_error,"storage_io_error"));legacy_primary_error=QUOTA_STORE_READ_OK;now_ms+=5000;tick(false);assert(durable_model.entry_count==3&&durable_model.refresh_seconds==900&&durable_model.screen_timeout_seconds==600&&legacy_primary_calls==2);}
else if(!strcmp(argv[1],"v2-reauth-cache")){seed_model();credentials[0].refresh_inflight=true;boot();assert(public_view.snapshot.accounts[0].five_hour.remaining_percent==17&&public_view.snapshot.accounts[0].status==QUOTA_STATUS_EXPIRED&&!strcmp(public_view.portable.account_errors[0],"auth_required"));assert(!query_calls&&!refresh_calls);}
else if(!strcmp(argv[1],"v2-ignores-legacy-io")){seed_model();legacy_primary_error=QUOTA_STORE_READ_IO_ERROR;boot();assert(public_view.snapshot.account_count==2&&legacy_primary_calls==0&&!s_storage_error[0]);}
else if(!strcmp(argv[1],"unknown-valid-prior")){boot();phone();model_unknown=true;quota_portable_command_t cmd={.op=QUOTA_PORTABLE_OP_SETTINGS_SAVE,.refresh_seconds=900,.screen_timeout_seconds=120};strcpy(cmd.request_id,"12345678");submit_command(&cmd);quota_model_t *held=s_dirty_model;now_ms+=1000;tick(true);assert(s_dirty_model==held&&!s_recovery_blocked&&public_view.refresh_seconds==300);model_unknown=false;now_ms+=5000;tick(true);assert(!s_dirty_model&&public_view.refresh_seconds==900);}
else assert(false);
puts("whole controller runtime passed");return 0;
}
