#!/usr/bin/env python3
"""Generate main/quota_wifi_icons.c: the status bar Wi-Fi glyph as small A8 (alpha) images.

    python3 tools/gen_wifi_icons.py            rewrite main/quota_wifi_icons.c
    python3 tools/gen_wifi_icons.py --check    fail if the committed file is not what this makes
    python3 tools/gen_wifi_icons.py --ascii    print every image as text

The glyph is a fan: a dot and three concentric arcs of 90 degrees with round ends. It is drawn
with 8 x 8 supersampling and needs no imaging library. The firmware tints each image with a style
color, so one set serves every state:

  lit[n]  the dot and the first n arcs (n = 1..3), drawn in the bright color
  dim[n]  what is left unlit at signal n (dim[0] is the whole glyph), drawn in the dim color
  slash   a diagonal stroke over the glyph, for a failed connection
"""

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "main" / "quota_wifi_icons.c"

WIDTH, HEIGHT = 17, 13
CENTER = (8.5, 11.5)  # the dot
DOT_RADIUS = 1.5
ARC_RADII = (4.5, 7.5, 10.5)  # middle of each arc's stroke, 3 px apart
ARC_THICKNESS = 1.45
HALF_ANGLE = math.radians(45)
SLASH = ((1.2, 12.2), (15.8, 1.8))
SLASH_THICKNESS = 1.6
SAMPLES = 8


def distance_to_segment(x, y, a, b):
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(x - (ax + t * dx), y - (ay + t * dy))


def in_dot(x, y):
    return math.hypot(x - CENTER[0], y - CENTER[1]) <= DOT_RADIUS


def in_arc(index, x, y):
    dx, dy = x - CENTER[0], CENTER[1] - y
    radius = math.hypot(dx, dy)
    half = ARC_THICKNESS / 2
    middle = ARC_RADII[index]
    if abs(radius - middle) <= half and dy > 0 and abs(math.atan2(dx, dy)) <= HALF_ANGLE:
        return True
    # Round ends: a disc of the stroke's width at each end of the arc.
    for sign in (-1, 1):
        ex = CENTER[0] + sign * middle * math.sin(HALF_ANGLE)
        ey = CENTER[1] - middle * math.cos(HALF_ANGLE)
        if math.hypot(x - ex, y - ey) <= half:
            return True
    return False


def in_slash(x, y):
    return distance_to_segment(x, y, *SLASH) <= SLASH_THICKNESS / 2


def render(shape):
    rows = []
    for row in range(HEIGHT):
        values = []
        for column in range(WIDTH):
            hits = 0
            for sy in range(SAMPLES):
                for sx in range(SAMPLES):
                    x = column + (sx + 0.5) / SAMPLES
                    y = row + (sy + 0.5) / SAMPLES
                    hits += shape(x, y)
            values.append(round(255 * hits / (SAMPLES * SAMPLES)))
        rows.append(values)
    return rows


def lit_shape(level):
    return lambda x, y: in_dot(x, y) or any(in_arc(i, x, y) for i in range(level))


def dim_shape(level):
    def shape(x, y):
        if level == 0 and in_dot(x, y):
            return True
        return any(in_arc(i, x, y) for i in range(level, 3))

    return shape


def images():
    result = [(f"lit_{n}", render(lit_shape(n))) for n in (1, 2, 3)]
    result += [(f"dim_{n}", render(dim_shape(n))) for n in range(4)]
    result.append(("slash", render(in_slash)))
    return result


def source():
    lines = [
        "/* Generated by tools/gen_wifi_icons.py: do not edit. */",
        '#include "quota_wifi_icons.h"',
        "",
        "#include <stdint.h>",
        "",
        "// clang-format off",
        "",
    ]
    for name, rows in images():
        lines.append(f"static const uint8_t s_{name}[] = {{")
        for row in rows:
            lines.append("    " + ",".join(f"0x{v:02x}" for v in row) + ",")
        lines.append("};")
    lines.append("")
    lines.append("#define ICON(bytes)                                                          \\")
    lines.append("    {                                                                        \\")
    lines.append("        .header.magic = LV_IMAGE_HEADER_MAGIC,                               \\")
    lines.append("        .header.cf = LV_COLOR_FORMAT_A8,                                     \\")
    lines.append(f"        .header.w = {WIDTH},                                                      \\")
    lines.append(f"        .header.h = {HEIGHT},                                                      \\")
    lines.append(f"        .header.stride = {WIDTH},                                                 \\")
    lines.append("        .data_size = sizeof(bytes),                                          \\")
    lines.append("        .data = bytes,                                                       \\")
    lines.append("    }")
    lines.append("")
    lines.append("const lv_image_dsc_t quota_wifi_lit[3] = {")
    lines.append("    ICON(s_lit_1), ICON(s_lit_2), ICON(s_lit_3),")
    lines.append("};")
    lines.append("const lv_image_dsc_t quota_wifi_dim[4] = {")
    lines.append("    ICON(s_dim_0), ICON(s_dim_1), ICON(s_dim_2), ICON(s_dim_3),")
    lines.append("};")
    lines.append("const lv_image_dsc_t quota_wifi_slash = ICON(s_slash);")
    lines.append("")
    return "\n".join(lines)


def main():
    arguments = sys.argv[1:]
    if "--ascii" in arguments:
        for name, rows in images():
            print(name)
            for row in rows:
                print("".join(" .:-=+*#%@"[min(9, v * 10 // 256)] for v in row))
        return
    text = source()
    if "--check" in arguments:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit("main/quota_wifi_icons.c is not what tools/gen_wifi_icons.py makes")
        return
    OUTPUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
